In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

## import DataSet

In [3]:
data = pd.read_csv(r"D:\JUPYTER_WORK\$um!T\4.Machine_learning\Linear Regression\Linear_Regression\DataSets\HousePricePrediction.csv")
df = pd.DataFrame(data)
df.sample(3)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
256,256,60,FV,8791,Inside,1Fam,5,2003,2003,VinylSd,0.0,864.0,207500.0
2479,2479,80,RL,14149,Inside,1Fam,8,1964,2001,HdBoard,722.0,980.0,NaN
697,697,20,RL,6420,Inside,1Fam,7,1952,1952,Wd Sdng,551.0,980.0,123500.0

## Data_set Cleaning

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [5]:
df = df.dropna()

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1460 non-null   int64
 1   MSSubClass    1460 non-null   int64
 2   MSZoning      1460 non-null   object
 3   LotArea       1460 non-null   int64
 4   LotConfig     1460 non-null   object
 5   BldgType      1460 non-null   object
 6   OverallCond   1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   Exterior1st   1460 non-null   object
 10  BsmtFinSF2    1460 non-null   float64
 11  TotalBsmtSF   1460 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 159.7+ KB

In [7]:
df['MSZoning'].unique()

array(['RL', 'RM', 'C (all)', 'FV', 'RH'], dtype=object)

In [8]:
df['MSZoning'] = df['MSZoning'].map({
    "RL":1,
    "RM":2,
    "C (all)":3,
    "FV":4,
    "RH":5
})

In [9]:
df["LotConfig"].unique()

array(['Inside', 'FR2', 'Corner', 'CulDSac', 'FR3'], dtype=object)

In [10]:
df["LotConfig"]=df["LotConfig"].map({
    "Inside":1,
    "FR2":2,
    "Corner":3,
    "CulDSac":4,
    "FR3":5
})

In [11]:
df["BldgType"].unique()

array(['1Fam', '2fmCon', 'Duplex', 'TwnhsE', 'Twnhs'], dtype=object)

In [12]:
df["BldgType"]=df["BldgType"].map({
    '1Fam':1,
    '2fmCon':2, 
    'Duplex':3, 
    'TwnhsE':4, 
    'Twnhs':5
})

## model INPUT / Output

In [13]:
df.sample(3)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
736,736,90,1,8544,1,3,4,1950,1950,Stucco,0.0,0.0,93500.0
616,616,60,1,7861,1,1,5,2002,2003,VinylSd,0.0,783.0,183200.0
829,829,160,4,2544,1,5,5,2005,2005,MetalSd,0.0,600.0,147400.0

In [14]:
X = df.drop(["Exterior1st","SalePrice"],axis=1)
y = df.SalePrice

## Train_test_split

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## Train Model / predict

In [16]:
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [17]:
Y_predict=model.predict(X_test)

## check r2_score

In [18]:
r2 = r2_score(Y_test,Y_predict)

In [19]:
r2

0.6174147995226935

## feature Engineering

In [20]:
df.sample(3)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
1219,1219,160,2,1680,1,5,5,1971,1971,CemntBd,0.0,672.0,91500.0
541,541,60,1,11000,2,1,5,2000,2000,VinylSd,0.0,969.0,248000.0
840,840,70,5,12155,1,1,8,1925,1950,Wd Sdng,0.0,672.0,140000.0

In [21]:
df["Exterior1st"].unique()

array(['VinylSd', 'MetalSd', 'Wd Sdng', 'HdBoard', 'BrkFace', 'WdShing',
       'CemntBd', 'Plywood', 'AsbShng', 'Stucco', 'BrkComm', 'AsphShn',
       'Stone', 'ImStucc', 'CBlock'], dtype=object)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1460 non-null   int64
 1   MSSubClass    1460 non-null   int64
 2   MSZoning      1460 non-null   int64
 3   LotArea       1460 non-null   int64
 4   LotConfig     1460 non-null   int64
 5   BldgType      1460 non-null   int64
 6   OverallCond   1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   Exterior1st   1460 non-null   object
 10  BsmtFinSF2    1460 non-null   float64
 11  TotalBsmtSF   1460 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(9), object(1)
memory usage: 159.7+ KB

In [23]:
df["Exterior1st"] = df["Exterior1st"].map({
    'VinylSd': 1,
    'MetalSd': 2,
    'Wd Sdng': 3,
    'HdBoard': 4,
    'BrkFace': 5,
    'WdShing': 6,
    'CemntBd': 7,
    'Plywood': 8,
    'AsbShng': 9,
    'Stucco': 10,
    'BrkComm': 11,
    'AsphShn': 12,
    'Stone': 13,
    'ImStucc': 14,
    'CBlock': 15
})

In [24]:
X = df.drop("SalePrice",axis=1)
y = df.SalePrice

In [25]:
df.tail(3)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
1457,1457,70,1,9042,1,1,9,1941,2006,7,0.0,1152.0,266500.0
1458,1458,20,1,9717,1,1,6,1950,1996,2,1029.0,1078.0,142125.0
1459,1459,20,1,9937,1,1,6,1965,1965,4,290.0,1256.0,147500.0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            1460 non-null   int64
 1   MSSubClass    1460 non-null   int64
 2   MSZoning      1460 non-null   int64
 3   LotArea       1460 non-null   int64
 4   LotConfig     1460 non-null   int64
 5   BldgType      1460 non-null   int64
 6   OverallCond   1460 non-null   int64
 7   YearBuilt     1460 non-null   int64
 8   YearRemodAdd  1460 non-null   int64
 9   Exterior1st   1460 non-null   int64
 10  BsmtFinSF2    1460 non-null   float64
 11  TotalBsmtSF   1460 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(10)
memory usage: 159.7 KB

In [27]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
model = LinearRegression()

In [29]:
model.fit(X_train,Y_train)

LinearRegression()

In [30]:
Y_predict=model.predict(X_test)

In [31]:
r3 = r2_score(Y_test,Y_predict)

In [32]:
r2

0.6174147995226935

In [33]:
r3

0.6180198072680192

## One Hot Encodeing

In [50]:
data = pd.read_csv(r"D:\JUPYTER_WORK\$um!T\4.Machine_learning\Linear Regression\Linear_Regression\DataSets\HousePricePrediction.csv")
df1 = pd.DataFrame(data)
df1.sample(3)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
1523,1523,20,RL,10950,Inside,1Fam,7,1952,1952,WdShing,0.0,864.0,NaN
1933,1933,60,RL,8702,Inside,1Fam,5,1997,1998,VinylSd,0.0,926.0,NaN
336,336,20,RL,14157,Corner,1Fam,5,2005,2006,VinylSd,0.0,1922.0,377426.0

In [51]:
df1 = df1.dropna()

In [52]:
df1 = pd.get_dummies(df1,columns=['MSZoning','LotConfig','BldgType','Exterior1st'],dtype=int,drop_first=True)

In [53]:
X = df1.drop('SalePrice',axis=1)
y = df1.SalePrice

In [54]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model = LinearRegression()
model.fit(X_train,Y_train)
Y_predict=model.predict(X_test)
r4 = r2_score(Y_test,Y_predict)

In [55]:
r3

0.6180198072680192

In [56]:
r4

0.6196387511449795

## by Gemini

In [59]:
data = pd.read_csv(r"D:\JUPYTER_WORK\$um!T\4.Machine_learning\Linear Regression\Linear_Regression\DataSets\HousePricePrediction.csv")
df = pd.DataFrame(data)
df.sample(3)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
2338,2338,20,RL,10612,Inside,1Fam,5,2006,2006,VinylSd,0.0,1524.0,NaN
2660,2660,20,RL,13758,Inside,1Fam,5,2005,2006,VinylSd,0.0,1792.0,NaN
1964,1964,160,RL,2308,FR2,TwnhsE,6,1975,1975,Plywood,294.0,855.0,NaN

In [60]:
import pandas as pd
import numpy as np

# Assuming 'df' is your DataFrame loaded from the CSV
# df = pd.read_csv(r"D:\JUPYTER_WORK\$um!T\4.Machine_learning\Linear Regression\Linear_Regression\DataSets\HousePricePrediction.csv")

# --- 0. Pre-processing: Handle Missing Values ---
# (Essential before creating features to avoid errors)
# Fill numeric nulls with 0 or mean, and categorical with mode or 'None'
if 'TotalBsmtSF' in df.columns:
    df['TotalBsmtSF'] = df['TotalBsmtSF'].fillna(0)
if 'BsmtFinSF2' in df.columns:
    df['BsmtFinSF2'] = df['BsmtFinSF2'].fillna(0)

# Fill categorical missing values (simple approach for this example)
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# --- 1. Log Transformation ---
# Handle skewness in LotArea
df['Log_LotArea'] = np.log1p(df['LotArea'])

# --- 2. Derived Features ---
# Years between building and remodeling
df['Years_Before_Remodel'] = df['YearRemodAdd'] - df['YearBuilt']

# Binary flag: Has the house been renovated? (1 if yes, 0 if no)
df['Has_Renovation'] = (df['YearRemodAdd'] != df['YearBuilt']).astype(int)

# Binary flag: Has a basement?
df['Has_Basement'] = (df['TotalBsmtSF'] > 0).astype(int)

# --- 3. Interaction Features ---
# Interaction: Condition * Size (Log)
df['Interaction_Cond_LogLot'] = df['OverallCond'] * df['Log_LotArea']

# Helper feature for age interaction: Years since 1900 (to keep numbers smaller/stable)
df['Years_Since_1900'] = df['YearBuilt'] - 1900

# Interaction: Condition * Age
df['Interaction_Cond_Age'] = df['OverallCond'] * df['Years_Since_1900']

# --- 4. Polynomial Features ---
# Squared terms to capture non-linear effects
df['OverallCond_Squared'] = df['OverallCond'] ** 2
df['Log_LotArea_Squared'] = df['Log_LotArea'] ** 2

# --- 5. One-Hot Encoding ---
# Convert all categorical variables to numeric binaries for Linear Regression
# drop_first=True is recommended for Linear Regression to avoid multicollinearity (dummy variable trap)
df_final = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Display result
print("Feature Engineering Complete.")
print(f"Original shape: {df.shape}")
print(f"New shape: {df_final.shape}")
print(df_final.head())

Feature Engineering Complete.
Original shape: (2919, 22)
New shape: (2919, 44)
   Id  MSSubClass  LotArea  OverallCond  YearBuilt  YearRemodAdd  BsmtFinSF2  \
0   0          60     8450            5       2003          2003         0.0
1   1          20     9600            8       1976          1976         0.0
2   2          60    11250            5       2001          2002         0.0
3   3          70     9550            5       1915          1970         0.0
4   4          60    14260            5       2000          2000         0.0

   TotalBsmtSF  SalePrice  Log_LotArea  ...  Exterior1st_CemntBd  \
0        856.0   208500.0     9.042040  ...                False
1       1262.0   181500.0     9.169623  ...                False
2        920.0   223500.0     9.328212  ...                False
3        756.0   140000.0     9.164401  ...                False
4       1145.0   250000.0     9.565284  ...                False

   Exterior1st_HdBoard  Exterior1st_ImStucc  Exterior1st_MetalSd  \
0                False                False                False
1                False                False                 True
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior1st_Plywood  Exterior1st_Stone  Exterior1st_Stucco  \
0                False              False               False
1                False              False               False
2                False              False               False
3                False              False               False
4                False              False               False

   Exterior1st_VinylSd  Exterior1st_Wd Sdng  Exterior1st_WdShing
0                 True                False                False
1                False                False                False
2                 True                False                False
3                False                 True                False
4                 True                False                False

[5 rows x 44 columns]

In [61]:
df_final.sample()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,Log_LotArea,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
900,900,20,7340,6,1971,1971,0.0,858.0,110000.0,8.90123,...,False,True,False,False,False,False,False,False,False,False

In [67]:
X = df_final.drop("SalePrice",axis=1)
y = df_final.SalePrice

In [68]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 43 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Id                       2919 non-null   int64
 1   MSSubClass               2919 non-null   int64
 2   LotArea                  2919 non-null   int64
 3   OverallCond              2919 non-null   int64
 4   YearBuilt                2919 non-null   int64
 5   YearRemodAdd             2919 non-null   int64
 6   BsmtFinSF2               2919 non-null   float64
 7   TotalBsmtSF              2919 non-null   float64
 8   Log_LotArea              2919 non-null   float64
 9   Years_Before_Remodel     2919 non-null   int64
 10  Has_Renovation           2919 non-null   int64
 11  Has_Basement             2919 non-null   int64
 12  Interaction_Cond_LogLot  2919 non-null   float64
 13  Years_Since_1900         2919 non-null   int64
 14  Interaction_Cond_Age     2919 non-null   int64
 15  OverallCond_Squared      2919 non-null   int64
 16  Log_LotArea_Squared      2919 non-null   float64
 17  MSZoning_FV              2919 non-null   bool
 18  MSZoning_RH              2919 non-null   bool
 19  MSZoning_RL              2919 non-null   bool
 20  MSZoning_RM              2919 non-null   bool
 21  LotConfig_CulDSac        2919 non-null   bool
 22  LotConfig_FR2            2919 non-null   bool
 23  LotConfig_FR3            2919 non-null   bool
 24  LotConfig_Inside         2919 non-null   bool
 25  BldgType_2fmCon          2919 non-null   bool
 26  BldgType_Duplex          2919 non-null   bool
 27  BldgType_Twnhs           2919 non-null   bool
 28  BldgType_TwnhsE          2919 non-null   bool
 29  Exterior1st_AsphShn      2919 non-null   bool
 30  Exterior1st_BrkComm      2919 non-null   bool
 31  Exterior1st_BrkFace      2919 non-null   bool
 32  Exterior1st_CBlock       2919 non-null   bool
 33  Exterior1st_CemntBd      2919 non-null   bool
 34  Exterior1st_HdBoard      2919 non-null   bool
 35  Exterior1st_ImStucc      2919 non-null   bool
 36  Exterior1st_MetalSd      2919 non-null   bool
 37  Exterior1st_Plywood      2919 non-null   bool
 38  Exterior1st_Stone        2919 non-null   bool
 39  Exterior1st_Stucco       2919 non-null   bool
 40  Exterior1st_VinylSd      2919 non-null   bool
 41  Exterior1st_Wd Sdng      2919 non-null   bool
 42  Exterior1st_WdShing      2919 non-null   bool
dtypes: bool(26), float64(5), int64(12)
memory usage: 461.9 KB

In [69]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=42)
model = LinearRegression()
model.fit(X_train,Y_train)
Y_predict=model.predict(X_test)
r4 = r2_score(Y_test,Y_predict)

ValueError: Input y contains NaN.